### ISSUE TITLE
whoami-v2-https-ssl-localhost

### ISSUE THREAD

**Issue by majidalikhn** [Heziode/traefik-v2-https-ssl-localhost#1]
I ran this one and it works like a charm and we can access the dashboard with https, I was wondering, what should be done and what steps should be taken to run the whoami with https aswell? Any insights and ideas about this?

**Comment by Heziode** [comment]
When you start the whoami services via `docker-compose -f whoami.yml up` it is already configured to use https, and accessible through : [whoami.docker.localhost](https://whoami.docker.localhost)

**Comment by majidalikhn** [comment]
Hi Quentin,

Thank you very much for the reply, that was awesome, I was using it wrong,
you saved my day. Thanks, have a nice day ahead.

*---*

*Mit freundlichen Grüßen*

*Majid Ali Khan*

*Technische Universität Chemnitz* | Master of Science in Automotive
Software Engineering
*CoreMedia GmbH* | Technical Consultant
T: +49 (17) 759 944 90

**Comment by Heziode** [comment]
No problem.

To get an exemple of configuration for other services, you can take a look at [whoami.yml](https://github.com/Heziode/traefik-v2-https-ssl-localhost/blob/master/whoami.yml).

More accuratly, every time you want to add a service that should be accessible through the web protocol, you can set up labels in your `docker-compose` file like this:

```yaml
      # Enable this container to be mapped by traefik
      # For more information, see: https://docs.traefik.io/providers/docker/#exposedbydefault
      - "traefik.enable=true"
      # The bellow instruction is MANDATORY if your container have multiple networks
      - "traefik.docker.network=proxy"
      # URL to reach this container
      - "traefik.http.routers.<service_name>.rule=Host(`my-sub-domain.docker.localhost`)"
      # Activation of TLS
      - "traefik.http.routers.<service_name>.tls=true"
      # If port is different than 80, use the following service:
      - "traefik.http.services.<service_name>.loadbalancer.server.port=<port>"
```
