### ISSUE TITLE
Specific domain

### ISSUE THREAD

**Issue by Renrhaf** [Heziode/traefik-v2-https-ssl-localhost#2]
Hi and thank you very much for this repo and documentation. It helps a lot !
I was wondering how to configure everything properly so that I could access containers from an other domain than the "docker.localhost" one ?

**Comment by Heziode** [comment]
Hi,

If you want to use a domain other than `docker.localhost`, choose whatever you want (however, I've not tested an overriding of TLD, so I don't know if `website.com` works).

suppose you want to replace `docker.localhost` by `foo.bar`:

You have to generate the SSL certificate with: `mkcert -cert-file certs/local-cert.pem -key-file certs/local-key.pem "foo.bar" "*.foo.bar"`

You also needs to update `traefik/config.yml` to use the `main` and `san` of `foo.bar` and update the rule for `Traefik` (`traefik.foo.bar` for example) and for every containers you have behind Traefik

**Comment by Renrhaf** [comment]
Thanks @Heziode, it seems like it works properly for a domain with TLD ".loc" for example.
I just had to restart a few things since the changes in /etc/hosts were not taken into account properly.
Again, thank you for this repo, it helped me switch to traefik v2 quite easily.
